language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t reinforcement-learning/web -f Dockerfile.dev .

script:
    - docker run -e CI=true reinforcement-learning/web npm run test -- --coverage
